name: "Chatbot Server"
version: "1.0.0"
slug: chatbot_server
description: "Flask server to receive questions from ESP32, send them to OpenAI, and return responses."
arch:
  - amd64
  - arm64
startup: services
boot: auto
ports:
  5000/tcp: 5000

options:
  openai_api_key: ""

schema:
  openai_api_key: str
