build_from:
  aarch64: "alpine:3.19"
  amd64: "alpine:3.19"
  armv7: "alpine:3.19"
labels:
  org.opencontainers.image.title: "School Chatbot WebSocket Server"
  org.opencontainers.image.description: "AI chatbot for ESP32 school devices"
  org.opencontainers.image.source: "https://github.com/paulsteigel/ha-chatbot-server"
  org.opencontainers.image.licenses: "MIT"
