build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11
labels:
  org.opencontainers.image.title: "School Chatbot WebSocket Server"
  org.opencontainers.image.description: "AI chatbot for ESP32 school devices"
  org.opencontainers.image.source: "https://github.com/paulsteigel/ha-chatbot-server"
  org.opencontainers.image.licenses: "MIT"
